### PR TITLE
TCP server

### PR DESCRIPTION
**Pull request by ed-asriyan**

### CODE REVIEW

**Review by TheKatarGit — APPROVED** [review]
LGTM

**Comment by yaches** [comment]
It's OK

**Review by yaches — COMMENTED** [review]
It's OK

**Comment by TheKatarGit** [comment]
Who's gonna merge this? Lol

**Review by yaches — CHANGES_REQUESTED** [review]
.

**Comment by yaches** [comment]
comment

**Comment by TheKatarGit** [comment]
You should either approve it, or declined by

**Comment by TheKatarGit** [comment]
*decline it

**Review by yaches — APPROVED** [review]

**Pull request merged**
